#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# update the package lists
apt-get update

# installs nginx server
apt-get install nginx -y


# Creates the /etc/nginx/html directory, which will serve as the document root directory for Nginx.
mkdir /etc/nginx/html

# creates the content of the index.html file.
echo "Hello World!" > /etc/nginx/html/index.html

# sets Nginx to listen on port 80 and serve files from /etc/nginx/html directory

echo "server {
     listen    80 default_server;
     listen    [::]:80 default_server;
     root      /etc/nginx/html;
     index     index.html index.htm;
}
" > /etc/nginx/sites-available/default

# configure server for redirection

echo "server {
     listen    80 default_server;
     listen    [::]:80 default_server;
     root      /var/www/html;
     index     index.html index.htm index.nginx-debian.html;

     location /redirect_me {
          return 301 https://example.com;
     }
}
" > /etc/nginx/sites-available/default


# Reload Nginx service to apply configuration chanages
service nginx restart
