#!/usr/bin/env bash
# set X-Served-By header to the current server

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;

   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://github.com/SHEFOO10;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }  
}" > default
sudo mv -f default /etc/nginx/sites-available/default

sed "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf > nginx.conf
sudo mv -f nginx.conf /etc/nginx/nginx.conf

sudo service nginx restart
