#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get update;
sudo apt-get install haproxy -y;

sudo sh -c 'echo "ENABLED=1" >> haproxy'

echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 34.224.63.137:80 check
        server web2 100.25.192.100:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
