#!/usr/bin/env bash
# Install and configure HAproxy

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get install haproxy=2.9.\* -y

sudo sed '/errorfile 504 \/etc\/haproxy\/errors\/504.http/a\\nfrontend my_frontend\n\tbind 0.0.0.0:80\n\tdefault_backend my_backend\n\nbackend my_backend\n\tbalance roundrobin\n\tserver server1 34.224.63.137\n\tserver server2 100.25.192.100\n' /etc/haproxy/haproxy.cfg > haproxy.cfg
sudo mv -f haproxy.cfg /etc/haproxy/haproxy.cfg

sudo service haproxy restart
