#!/usr/bin/env bash
# install and run nginx service
sudo apt-get update -y
sudo apt-get install nginx -y
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
