#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
Hours=0 minutes=1
while [ $Hours -le 12 ];
do
	echo "Hour: $Hours"
	while [ $minutes -le 59 ];
	do
		echo "$minutes"
		((minutes++))
	done
	minutes=1
	((Hours++))
done

