#!/usr/bin/env bash
# display content of the current directory

for file in *; do
    # Extract the part of the name after the first dash
    name_after_dash=$(echo "$file" | cut -d'-' -f2)
    
    # Display the result
    echo "$name_after_dash"
done
