#!/usr/bin/env bash
# fix web server container have apache2 not running

# first download and create container with name Alx 
sudo docker run -p 8080:80 --name Alx -d -it holbertonschool/265-0

sudo docker exec -it Alx /bin/bash -c 'echo "ServerName $(hostname)" >> /etc/apache2/apache2.conf';

# second execute service apache2 start
sudo docker exec -it Alx /bin/bash -c 'service apache2 start'
