#!/usr/bin/env bash
# 1. Run Nginx as Nginx
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
